apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "bigmoji.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bigmoji.name" . }}
    helm.sh/chart: {{ include "bigmoji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bigmoji.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bigmoji.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: DISCORD_TOKEN
            valueFrom: 
              secretKeyRef:
                name: {{ .Values.secrets.discord }}
                key: DISCORD_TOKEN